sfdx-source/Modules/mail/objects/MailMessage__c/MailMessage__c.object-meta.xml
<CustomObject>
    <description>Represents a single mail message in a mail client.</description>
    <label>Mail Message</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mail Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/Modules/mail/objects/MailMessage__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <description>The body of the sent message.</description>
    <inlineHelpText>Enter the body of the message to be sent.</inlineHelpText>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/Modules/mail/objects/MailMessage__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>The Contact this message was sent to.</description>
    <inlineHelpText>Enter the Contact this message was sent to.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>ContactMessages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/Modules/mail/objects/MailMessage__c/fields/DateSent__c.field-meta.xml
<CustomField>
    <fullName>DateSent__c</fullName>
    <defaultValue>Now()</defaultValue>
    <description>The date and time this message was sent.</description>
    <inlineHelpText>Enter the date and time this message was sent.</inlineHelpText>
    <label>Date Sent</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

sfdx-source/Modules/mail/objects/MailMessage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the message, especially whether it was sent or whether there were errors sending.</description>
    <inlineHelpText>Status of the message, especially whether it was sent or whether there were errors sending.</inlineHelpText>
    <label>Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/Modules/mail/objects/MailMessage__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>The subject of the sent message.</description>
    <inlineHelpText>Enter the subject of the sent message, if any.</inlineHelpText>
    <label>Subject</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/Modules/ocdla-mail/classes/ExpertWitnessMailAction.cls
public class ExpertWitnessMailAction implements IMailEventAction {
    
    public void afterSend(List<MailSendStatus> results) {
        
		List<MailMessage__c> messages = new List<MailMessage__c>();
         
        for(MailSendStatus status :results) {

            MailMessage__c m = new MailMessage__c(Contact__c=status.targetObjectId, 
                                                  Subject__c=status.subject,
                                                  Body__c=status.body,
                                                  DateSent__c=status.dateSent,
                                                  Status__c=status.message);
                                                  m.Name = status.subject + ' - ' + status.dateSent.format();
            
            messages.add(m);
        }  
        
        insert messages;
    }
}